### ISSUE TITLE
Desktop applications only support the oauth_callback value 'oob'

### ISSUE THREAD

**Issue by mitulmarsonia** [naoto0n2/iOS11-TwitterShareSample#1]
Hello, Nice work,
when i try to run app getting error like this:-

```
<hash>
  <error>Desktop applications only support the oauth_callback value 'oob'</error>
  <request>/oauth/request_token</request>
</hash>
" UserInfo={NSLocalizedDescription=<?xml version="1.0" encoding="UTF-8"?>
<hash>
  <error>Desktop applications only support the oauth_callback value 'oob'</error>
  <request>/oauth/request_token</request>
</hash>
```

I have enter following key,
`Twitter.sharedInstance().start(withConsumerKey:"8fWJDIlNvMSL4NK8Rlrsokymv", consumerSecret:"w69BllMkm0mG2VOE8WqcVwuHaKHYD5gUcFr2EOfmpWBRaiFik1")`
        
Info.plist
twitterkit-8fWJDIlNvMSL4NK8Rlrsokymv

Can you please help me out.

**Comment by mofneko** [comment]
please make sure your callback setting is set in your app settings on apps.twitter.com
If the callback setting is blank, it is recognized as a desktop application and can not be used with this method
Please specify some valid URL

**Comment by mofneko** [comment]
Please make sure your callback setting is set in your app settings on apps.twitter.com
If the callback setting is blank, it is recognized as a desktop application and can not be used with this method
Please specify some valid URL
